add geocoordinates to Point table in DB
starwit/databackend pull request #25
Opened 2024-02-28 13:41 UTC by flostyl3

## Description

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-02-28 14:09 UTC, witchpou requested changes

2024-02-28 14:09 UTC, witchpou commented on persistence/src/main/resources/db/migration/databackend/V1_4__addgeocoordinnates.sql
please add also entities
georeferenced is missing

2024-02-28 14:50 UTC, witchpou commented on persistence/src/main/resources/db/migration/databackend/V1_4__addgeocoordinnates.sql
> +ALTER TABLE "point" ADD "longitude" Decimal(20,17);
why (20,17)?...I used (22,19)

2024-03-01 10:37 UTC, flonix8 commented on persistence/src/main/resources/db/migration/databackend/V1_4__addgeocoordinnates.sql
I added the column `geo_referenced`. Should we use that or should I change it to `georeferenced`, because all other fields on `AnalyticsJobEntity` do not use snake case, the one on `PointEntity` do, however...

2024-03-05 12:33 UTC, witchpou approved these changes

2024-03-07 08:04 UTC, merged